### ISSUE TITLE
Does pkg: pkg have a purpose?

### ISSUE THREAD

**Issue by frodefi** [shprink/angular2-nobullshit-boilerplate#6]
In the webpack.config.js is the following

```
plugins: [new HtmlWebpackPlugin({
    filename: 'index.html',
    pkg: pkg,
    template: path.join(libPath, 'index.html')
}
```

I cannot see the optoin `pkg` in the docs for [HtmlWebpackPlugin](https://github.com/ampedandwired/html-webpack-plugin)...

**Comment by shprink** [comment]
Yes pkg is package.json. Using HtmlPlugin we can use any property of package.json in our index.html file.

We can get the name or the version for instance: https://github.com/shprink/angular2-nobullshit-boilerplate/blob/master/lib/index.html#L10-L11

**Comment by frodefi** [comment]
Aha, that makes sense :) Thanks!
